"""add email verification fields

Revision ID: 76f1184b2fb4
Revises: 97a3c96dd103
Create Date: 2025-08-01 14:53:50.473541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76f1184b2fb4'
down_revision = '97a3c96dd103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('verification_code_sent_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verification_expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oauth_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('verification_code_sent_at')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
