"""add fireflies_transcript_id to meeting

Revision ID: bf9b30b979b9
Revises: 
Create Date: 2025-05-26 12:11:14.893772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9b30b979b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fireflies_transcript_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('transcription',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('transcription',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('fireflies_transcript_id')

    # ### end Alembic commands ###
