"""add audio_url and video_url to meeting

Revision ID: d83159f8bf9b
Revises: bf9b30b979b9
Create Date: 2025-05-26 12:29:22.229775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83159f8bf9b'
down_revision = 'bf9b30b979b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
